SELECT Kontinent, AVG(CAST(KolNas AS FLOAT)/PL) AS PL_PLotn
FROM Tabl_Kontinent$
WHERE PL > 1000000
GROUP BY Kontinent
HAVING AVG(CAST(KolNas AS FLOAT)/PL) > 10
ORDER BY AVG(CAST(KolNas AS FLOAT)/PL) DESC;